;; This logfile was generated automatically by `xindy'
;; at 19.05.2016  17:46:42
;; Indexstyle: "/var/folders/lx/wpzn2jyx7r96s76gn7h5cyd40000gn/T/vGAdLdtGFW", Rawindex: "/var/folders/lx/wpzn2jyx7r96s76gn7h5cyd40000gn/T/gGDPMQRKCw", Output: "main.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "„" -> "G"
Letter-group: "¨È" -> "I"
Letter-group: "„È" -> "B"
Letter-group: "€Ð" -> "A"
Letter-group: "ÚÈ†" -> "T"
Letter-group: "¨Èå6" -> "I"
Letter-group: "¨Èœ¨ë" -> "I"
Letter-group: "†Ðå" -> "C"
Letter-group: "È€" -> "D"
Letter-group: "Ðå" -> "S"
Letter-group: "†ÐÐ" -> "C"
Letter-group: "¤Ú»´" -> "H"
Letter-group: "ÃÐ" -> "D"
Letter-group: "¼Ú¼à" -> "N"
Letter-group: "´å»" -> "L"
Letter-group: "ÃÐ" -> "D"
Letter-group: "¨Èå4" -> "I"
Letter-group: "€È¨" -> "A"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "€È¨" -> "A"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "„È" -> "B"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "†ÐÐ" -> "C"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "ÃÐ" -> "D"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "„" -> "G"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¤Ú»´" -> "H"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¨È" -> "I"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "´å»" -> "L"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¼Ú¼à" -> "N"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ðå" -> "S"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "ÚÈ†" -> "T"